package dev.goose.compiler

import com.google.devtools.ksp.KspExperimental
import com.google.devtools.ksp.getAllSuperTypes
import com.google.devtools.ksp.isAbstract
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.FunctionKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSValueParameter
import com.google.devtools.ksp.symbol.Modifier
import com.google.devtools.ksp.validate

private const val GOOSE_UI = "dev.goose.runtime.GooseUi"
private const val GOOSE_FRAGMENT = "dev.goose.fragment.GooseFragment"
private const val FRAGMENT = "androidx.fragment.app.Fragment"
private const val MODIFIER = "androidx.compose.ui.Modifier"
private const val COMPOSABLE = "androidx.compose.runtime.Composable"
private const val MAVERICKS_VM = "com.airbnb.mvrx.MavericksViewModel"
private const val NAVIGATOR = "dev.goose.runtime.Navigator"
private const val ASSISTED_FACTORY = "dev.zacsweers.metro.AssistedFactory"
private const val DAGGER_ASSISTED_FACTORY = "dagger.assisted.AssistedFactory"
private const val SERIALIZABLE = "kotlinx.serialization.Serializable"
private const val APP_SCOPE = "dev.zacsweers.metro.AppScope"

/** Both DI worlds' assisted-factory markers; a migrating Dagger/Anvil app keeps its own. */
private val ASSISTED_FACTORY_ANNOTATIONS = setOf(ASSISTED_FACTORY, DAGGER_ASSISTED_FACTORY)

/** Internal names in the generated ScreenEntry lambda, reserved so user params can't shadow them. */
private val RESERVED_PARAM_NAMES = setOf("gooseScreen", "gooseModifier")

/**
 * Turns `@GooseUi(SomeScreen::class)` composable functions into the full Goose registration:
 * a Metro-contributed module whose @Provides function returns the ScreenEntry adapter, keyed by
 * the screen class. Parameters are wired by type:
 * - the screen class -> the screen being rendered
 * - [Modifier] -> the host's modifier
 * - a MavericksViewModel with a nested @AssistedFactory (Metro's or Dagger's) shaped
 *   `(State, Navigator) -> VM` -> a generated `screenViewModel` call (the factory itself is
 *   injected from the graph)
 * - that ViewModel's state class (exact type) -> a generated `collectAsState().value`
 * - anything else -> an injected provider parameter, resolved from the graph at compile time,
 *   with Metro qualifier annotations copied over
 *
 * Supported grammar: public or internal, top-level, non-suspend, non-generic, non-extension
 * `@Composable` functions taking a `@Serializable` screen. Anything else is a compile error
 * with a message naming the rule. Same-name functions are detected within a module; two Gradle
 * modules sharing one package could still generate colliding class names, so keep feature
 * packages distinct per module (the namespace every Android library module already declares).
 */
class GooseUiProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    /** (package, module name) pairs generated so far, to fail fast on name collisions. */
    private val generatedModules = mutableSetOf<Pair<String, String>>()

    /**
     * Functions whose ViewModel factory wasn't findable this round, keyed by function FQN with
     * the diagnostic to emit if no later round supplies it. A factory generated by the APP's
     * own processor lands in a later round, so the function defers instead of erroring; the
     * leftover diagnostics become errors in [finish].
     */
    private val awaitingFactory = linkedMapOf<String, String>()

    /** Set by [generate] when the missing factory may appear in a later round (app codegen). */
    private var retryForFactory: String? = null

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val deferred = mutableListOf<KSAnnotated>()
        for (symbol in resolver.getSymbolsWithAnnotation(GOOSE_UI)) {
            if (!symbol.validate()) {
                deferred += symbol
                continue
            }
            val function = symbol as? KSFunctionDeclaration ?: run {
                logger.error("@GooseUi is only valid on functions", symbol)
                continue
            }
            val key = function.qualifiedName?.asString() ?: function.simpleName.asString()
            retryForFactory = null
            generate(function, resolver)
            val retryMessage = retryForFactory
            if (retryMessage != null) {
                awaitingFactory[key] = retryMessage
                deferred += symbol
            } else {
                awaitingFactory.remove(key)
            }
        }
        for (symbol in resolver.getSymbolsWithAnnotation(GOOSE_FRAGMENT)) {
            if (!symbol.validate()) {
                deferred += symbol
                continue
            }
            val clazz = symbol as? KSClassDeclaration ?: run {
                logger.error("@GooseFragment is only valid on classes", symbol)
                continue
            }
            generateFragmentEntry(clazz)
        }
        return deferred
    }

    private fun validateShape(function: KSFunctionDeclaration): Boolean {
        fun err(message: String): Boolean {
            logger.error("@GooseUi: $message", function)
            return false
        }
        if (function.functionKind != FunctionKind.TOP_LEVEL) {
            return err("must be a top-level function (member and local functions are not supported)")
        }
        if (Modifier.PRIVATE in function.modifiers) {
            return err("must not be private (the generated registration lives in a separate file)")
        }
        if (function.extensionReceiver != null) {
            return err("must not be an extension function")
        }
        if (function.typeParameters.isNotEmpty()) {
            return err("must not be generic")
        }
        if (Modifier.SUSPEND in function.modifiers) {
            return err("must not be suspend")
        }
        val composable = function.annotations.any {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == COMPOSABLE
        }
        if (!composable) {
            return err("must be @Composable")
        }
        return true
    }

    override fun finish() {
        awaitingFactory.values.forEach { logger.error(it) }
    }

    private fun generate(function: KSFunctionDeclaration, resolver: Resolver) {
        if (!validateShape(function)) return
        val annotation = function.annotations.first { it.annotationType.resolve().declaration.qualifiedName?.asString() == GOOSE_UI }
        val screenType = annotation.classArgument("screen", index = 0) ?: run {
            logger.error("@GooseUi requires a screen class argument", function)
            return
        }
        val screenFqn = screenType.declaration.qualifiedName?.asString() ?: run {
            logger.error("@GooseUi screen class has no qualified name", function)
            return
        }
        val scopeFqn = annotation.classArgument("scope", index = 1)
            ?.declaration?.qualifiedName?.asString()
            .let { if (it == null || it == "kotlin.Unit") APP_SCOPE else it }
        // Fail here, not on the first state save: back-stack persistence needs the serializer.
        val screenSerializable = screenType.declaration.annotations.any {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == SERIALIZABLE
        }
        if (!screenSerializable) {
            logger.error(
                "@GooseUi screen ${screenType.declaration.simpleName.asString()} must be " +
                    "@Serializable (back stacks persist screens across process death)",
                function,
            )
            return
        }

        val packageName = function.packageName.asString()
        val functionName = function.simpleName.asString()
        val moduleName = "${functionName}GooseModule"
        // Checked here, ADDED just before the file write: a function deferred for its factory
        // (below) passes through again and must not collide with itself.
        if ((packageName to moduleName) in generatedModules) {
            logger.error(
                "@GooseUi: two annotated functions named '$functionName' in package '$packageName'. " +
                    "Generated registrations are named after the function; rename one.",
                function,
            )
            return
        }

        data class Injected(val name: String, val type: String, val qualifiers: String)
        data class VmParam(val name: String, val vmFqn: String, val stateFqn: String, val factoryFqn: String, val createName: String)

        val paramNames = function.parameters.mapNotNull { it.name?.asString() }
        for (reserved in RESERVED_PARAM_NAMES) {
            if (reserved in paramNames) {
                logger.error("@GooseUi: parameter name '$reserved' is reserved for generated code", function)
                return
            }
        }

        var hasScreenParam = false
        var hasModifierParam = false
        val injected = mutableListOf<Injected>()
        val vmParams = mutableListOf<VmParam>()

        // First pass: find ViewModel parameters, so state parameters can be matched to them.
        for (param in function.parameters) {
            val name = param.name?.asString() ?: continue
            val type = param.type.resolve()
            val decl = type.declaration as? KSClassDeclaration ?: continue
            val vmSuper = decl.getAllSuperTypes()
                .firstOrNull { it.declaration.qualifiedName?.asString() == MAVERICKS_VM }
                ?: continue
            val vmFqn = decl.qualifiedName?.asString() ?: continue
            val stateFqn = vmSuper.arguments.firstOrNull()?.type?.resolve()
                ?.declaration?.qualifiedName?.asString() ?: run {
                logger.error("Cannot resolve the state type of $vmFqn", param)
                return
            }
            val factory = findGooseFactory(decl, stateFqn, vmFqn, param, resolver) ?: return
            if (factory.first.isEmpty()) {
                // Defer: the factory may be another processor's output, arriving next round.
                // If it never arrives, finish() emits this diagnostic.
                retryForFactory =
                    "@GooseUi on '${function.simpleName.asString()}' cannot wire " +
                        "'$name: ${decl.simpleName.asString()}': no @AssistedFactory (Metro or Dagger) " +
                        "with a `(initialState, navigator)` create function, nested in the ViewModel " +
                        "or top-level in its package. For a screen-scoped ViewModel, add one (see the " +
                        "goose README). For a flow-shared ViewModel, call flowViewModel() inside the " +
                        "function instead of taking it as a parameter."
                return
            }
            vmParams += VmParam(name, vmFqn, stateFqn, factory.first, factory.second)
        }

        val callArgs = mutableListOf<String>()
        for (param in function.parameters) {
            val name = param.name?.asString() ?: run {
                logger.error("@GooseUi function parameters must be named", function)
                return
            }
            val type = param.type.resolve()
            val typeFqn = type.declaration.qualifiedName?.asString()
            val stateOwners = vmParams.filter { it.stateFqn == typeFqn }
            when {
                typeFqn == screenFqn -> {
                    hasScreenParam = true
                    callArgs += "$name = gooseScreen as $screenFqn"
                }
                typeFqn == MODIFIER -> {
                    hasModifierParam = true
                    callArgs += "$name = gooseModifier"
                }
                vmParams.any { it.name == name } -> callArgs += "$name = $name"
                stateOwners.size == 1 -> callArgs += "$name = ${stateOwners.single().name}.collectAsState().value"
                stateOwners.size > 1 -> {
                    logger.error(
                        "State parameter '$name' is ambiguous: ${stateOwners.size} ViewModel parameters share this state type",
                        param,
                    )
                    return
                }
                else -> {
                    injected += Injected(name, type.render(), param.renderQualifiers(logger, "@GooseUi", function) ?: return)
                    callArgs += "$name = $name"
                }
            }
        }

        val usedNames = paramNames.toMutableSet()
        val factoryParamNames = vmParams.associate { vm ->
            var candidate = "${vm.name}Factory"
            while (!usedNames.add(candidate)) candidate += "_"
            vm.name to candidate
        }
        for (vm in vmParams) {
            injected += Injected(factoryParamNames.getValue(vm.name), vm.factoryFqn, "")
        }

        val providerParams = injected.joinToString(",\n            ") { "${it.qualifiers}${it.name}: ${it.type}" }
        val lambdaParams = buildString {
            append(if (hasScreenParam || vmParams.isNotEmpty()) "gooseScreen" else "_")
            append(", ")
            append(if (hasModifierParam) "gooseModifier" else "_")
        }
        val imports = buildString {
            if (vmParams.isNotEmpty()) {
                append("\nimport dev.goose.mavericks.screenViewModel")
                if (callArgs.any { ".collectAsState()" in it }) append("\nimport com.airbnb.mvrx.compose.collectAsState")
            }
        }
        val vmDeclarations = vmParams.joinToString("") { vm ->
            "\n            val ${vm.name} = screenViewModel(gooseScreen, ${vm.vmFqn}::class.java, ${vm.stateFqn}::class.java, ${factoryParamNames.getValue(vm.name)}::${vm.createName})"
        }

        generatedModules.add(packageName to moduleName)
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, function.containingFile!!),
            packageName = packageName,
            fileName = moduleName,
        )
        file.bufferedWriter().use { writer ->
            writer.write(
                """
                |// Generated by goose-compiler from @GooseUi on $functionName. Do not edit.
                |@file:Suppress("UNCHECKED_CAST", "UNUSED_ANONYMOUS_PARAMETER")
                |package $packageName
                |$imports
                |
                |@dev.zacsweers.metro.ContributesTo($scopeFqn::class)
                |public interface $moduleName {
                |    public companion object {
                |        @dev.zacsweers.metro.Provides
                |        @dev.zacsweers.metro.IntoMap
                |        @dev.zacsweers.metro.ClassKey($screenFqn::class)
                |        public fun provide$functionName(
                |            $providerParams
                |        ): dev.goose.runtime.ScreenEntry = dev.goose.runtime.ScreenEntry { $lambdaParams ->$vmDeclarations
                |            $functionName(
                |                ${callArgs.joinToString(",\n                ")},
                |            )
                |        }
                |    }
                |}
                |""".trimMargin()
            )
        }
    }

    /**
     * Turns `@GooseFragment(SomeScreen::class)` fragment classes into the typed-fragment
     * registration that previously required a hand-written @Provides: a contributed module
     * whose entry renders the fragment via `fragmentScreenEntry`, with the Bundle built from
     * the screen's constructor properties BY NAME (`screen.termsId` -> `"termsId"`). The
     * convention is the whole feature: a fragment whose argument keys differ from the screen's
     * property names, or that needs Bundle entries beyond the screen's fields, keeps the
     * explicit `fragmentScreenEntry { }` registration.
     */
    private fun generateFragmentEntry(clazz: KSClassDeclaration) {
        fun err(message: String) = logger.error("@GooseFragment: $message", clazz)

        if (Modifier.PRIVATE in clazz.modifiers) {
            return err("must not be private (the generated registration lives in a separate file)")
        }
        if (clazz.isAbstract()) {
            return err("must not be abstract (the entry instantiates the fragment)")
        }
        if (clazz.getAllSuperTypes().none { it.declaration.qualifiedName?.asString() == FRAGMENT }) {
            return err("${clazz.simpleName.asString()} must extend androidx.fragment.app.Fragment")
        }

        val annotation = clazz.annotations.first {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == GOOSE_FRAGMENT
        }
        val screenType = annotation.classArgument("screen", index = 0)
            ?: return err("requires a screen class argument")
        val screenDecl = screenType.declaration as? KSClassDeclaration
            ?: return err("screen argument must be a class")
        val screenFqn = screenDecl.qualifiedName?.asString()
            ?: return err("screen class has no qualified name")
        val scopeFqn = annotation.classArgument("scope", index = 1)
            ?.declaration?.qualifiedName?.asString()
            .let { if (it == null || it == "kotlin.Unit") APP_SCOPE else it }
        val screenSerializable = screenDecl.annotations.any {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == SERIALIZABLE
        }
        if (!screenSerializable) {
            return err(
                "screen ${screenDecl.simpleName.asString()} must be @Serializable " +
                    "(back stacks persist screens across process death)"
            )
        }

        // The Bundle convention: every primary-constructor property, keyed by its own name.
        val params = screenDecl.primaryConstructor?.parameters.orEmpty()
        val pairs = params.map { param ->
            val name = param.name?.asString()
                ?: return err("screen constructor parameters must be named")
            if (!param.isVal && !param.isVar) {
                return err(
                    "screen constructor parameter '$name' must be a val/var property " +
                        "so the generated entry can read it"
                )
            }
            "\"$name\" to gooseScreen.$name"
        }

        val fragmentFqn = clazz.qualifiedName?.asString()
            ?: return err("fragment class has no qualified name")
        val fragmentName = clazz.simpleName.asString()
        val packageName = clazz.packageName.asString()
        val moduleName = "${fragmentName}GooseModule"
        if (!generatedModules.add(packageName to moduleName)) {
            return err("two @GooseFragment classes named '$fragmentName' in package '$packageName'; rename one")
        }

        val entryExpression = if (pairs.isEmpty()) {
            "dev.goose.fragment.fragmentScreenEntry<$fragmentFqn, $screenFqn>()"
        } else {
            """dev.goose.fragment.fragmentScreenEntry<$fragmentFqn, $screenFqn> { gooseScreen ->
                |            androidx.core.os.bundleOf(
                |                ${pairs.joinToString(",\n                |                ")},
                |            )
                |        }""".trimMargin()
        }

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, clazz.containingFile!!),
            packageName = packageName,
            fileName = moduleName,
        )
        file.bufferedWriter().use { writer ->
            writer.write(
                """
                |// Generated by goose-compiler from @GooseFragment on $fragmentName. Do not edit.
                |package $packageName
                |
                |@dev.zacsweers.metro.ContributesTo($scopeFqn::class)
                |public interface $moduleName {
                |    public companion object {
                |        @dev.zacsweers.metro.Provides
                |        @dev.zacsweers.metro.IntoMap
                |        @dev.zacsweers.metro.ClassKey($screenFqn::class)
                |        public fun provide$fragmentName(): dev.goose.runtime.ScreenEntry =
                |            $entryExpression
                |    }
                |}
                |""".trimMargin()
            )
        }
    }

    /**
     * Finds the ViewModel's goose assisted factory: an abstract function of shape
     * `(stateType, Navigator) -> vmType` (declared or inherited; other non-abstract members are
     * fine). Nested classifiers annotated `@AssistedFactory` are searched first; when none
     * match, any top-level `@AssistedFactory` in the VM's own package is tried — that's where
     * an app's factory codegen puts them, since processors can only emit top-level types.
     * Returns (factory FQN, create-function name), ("" to "") when the VM has none
     * (flow-shared VMs deliberately don't), or null after logging when more than one matches.
     */
    private fun findGooseFactory(
        vm: KSClassDeclaration,
        stateFqn: String,
        vmFqn: String,
        errorSite: KSValueParameter,
        resolver: Resolver,
    ): Pair<String, String>? {
        val nested = vm.declarations.filterIsInstance<KSClassDeclaration>()
            .filter { it.isAssistedFactory() }
            .toList()
        var matches = factoryMatches(nested, stateFqn, vmFqn)
        if (matches.isEmpty()) {
            @OptIn(KspExperimental::class)
            val packageCandidates = resolver.getDeclarationsFromPackage(vm.packageName.asString())
                .filterIsInstance<KSClassDeclaration>()
                .filter { it.parentDeclaration == null && it.isAssistedFactory() }
                .toList()
            matches = factoryMatches(packageCandidates, stateFqn, vmFqn)
        }
        return when {
            matches.isEmpty() -> "" to ""
            matches.size == 1 -> matches.single()
            else -> {
                logger.error(
                    "@GooseUi: $vmFqn has ${matches.size} @AssistedFactory create functions matching " +
                        "(state, navigator); keep exactly one",
                    errorSite,
                )
                null
            }
        }
    }

    private fun factoryMatches(
        candidates: List<KSClassDeclaration>,
        stateFqn: String,
        vmFqn: String,
    ): List<Pair<String, String>> {
        val matches = mutableListOf<Pair<String, String>>()
        for (candidate in candidates) {
            val factoryFqn = candidate.qualifiedName?.asString() ?: continue
            for (create in candidate.gooseCreateFunctions(stateFqn, vmFqn)) {
                matches += factoryFqn to create.simpleName.asString()
            }
        }
        return matches
    }

    private fun KSClassDeclaration.isAssistedFactory(): Boolean = annotations.any {
        it.annotationType.resolve().declaration.qualifiedName?.asString() in ASSISTED_FACTORY_ANNOTATIONS
    }

    private fun KSClassDeclaration.gooseCreateFunctions(
        stateFqn: String,
        vmFqn: String,
    ): Sequence<KSFunctionDeclaration> =
        getAllFunctions().filter { create ->
            val params = create.parameters
            create.isAbstract &&
                params.size == 2 &&
                params[0].type.resolve().declaration.qualifiedName?.asString() == stateFqn &&
                params[1].type.resolve().declaration.qualifiedName?.asString() == NAVIGATOR &&
                create.returnType?.resolve()?.declaration?.qualifiedName?.asString() == vmFqn
        }
}

class GooseUiProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        GooseUiProcessor(environment.codeGenerator, environment.logger)
}
