package dev.goose.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSValueParameter
import com.google.devtools.ksp.symbol.Nullability
import com.google.devtools.ksp.validate

private const val GOOSE_UI = "dev.goose.runtime.GooseUi"
private const val MODIFIER = "androidx.compose.ui.Modifier"

/**
 * Turns `@GooseUi(SomeScreen::class)` composable functions into the full Goose registration:
 * a Metro-contributed module whose @Provides function returns the ScreenEntry adapter, keyed by
 * the screen class. Parameters typed as the screen or Modifier are forwarded from the host;
 * every other parameter becomes an injected provider parameter.
 */
class GooseUiProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(GOOSE_UI)
        val deferred = mutableListOf<KSAnnotated>()
        for (symbol in symbols) {
            if (!symbol.validate()) {
                deferred += symbol
                continue
            }
            val function = symbol as? KSFunctionDeclaration ?: run {
                logger.error("@GooseUi is only valid on functions", symbol)
                continue
            }
            generate(function)
        }
        return deferred
    }

    private fun generate(function: KSFunctionDeclaration) {
        val annotation = function.annotations.first { it.annotationType.resolve().declaration.qualifiedName?.asString() == GOOSE_UI }
        val screenType = annotation.screenArgument() ?: run {
            logger.error("@GooseUi requires a screen class argument", function)
            return
        }
        val screenFqn = screenType.declaration.qualifiedName?.asString() ?: run {
            logger.error("@GooseUi screen class has no qualified name", function)
            return
        }
        val packageName = function.packageName.asString()
        val functionName = function.simpleName.asString()
        val moduleName = "${functionName}GooseModule"

        data class Injected(val name: String, val type: String)

        var hasScreenParam = false
        var hasModifierParam = false
        val callArgs = mutableListOf<String>()
        val injected = mutableListOf<Injected>()

        for (param in function.parameters) {
            val name = param.name?.asString() ?: run {
                logger.error("@GooseUi function parameters must be named", function)
                return
            }
            val type = param.type.resolve()
            val typeFqn = type.declaration.qualifiedName?.asString()
            when {
                typeFqn == screenFqn -> {
                    hasScreenParam = true
                    callArgs += "$name = screen as $screenFqn"
                }
                typeFqn == MODIFIER -> {
                    hasModifierParam = true
                    callArgs += "$name = modifier"
                }
                else -> {
                    injected += Injected(name, type.render())
                    callArgs += "$name = $name"
                }
            }
        }

        val providerParams = injected.joinToString(",\n            ") { "${it.name}: ${it.type}" }
        val lambdaParams = buildString {
            append(if (hasScreenParam) "screen" else "_")
            append(", ")
            append(if (hasModifierParam) "modifier" else "_")
        }

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, function.containingFile!!),
            packageName = packageName,
            fileName = moduleName,
        )
        file.bufferedWriter().use { writer ->
            writer.write(
                """
                |// Generated by goose-compiler from @GooseUi on $functionName. Do not edit.
                |@file:Suppress("UNCHECKED_CAST", "UNUSED_ANONYMOUS_PARAMETER")
                |package $packageName
                |
                |@dev.zacsweers.metro.ContributesTo(dev.zacsweers.metro.AppScope::class)
                |public interface $moduleName {
                |    public companion object {
                |        @dev.zacsweers.metro.Provides
                |        @dev.zacsweers.metro.IntoMap
                |        @dev.zacsweers.metro.ClassKey($screenFqn::class)
                |        public fun provide$functionName(
                |            $providerParams
                |        ): dev.goose.runtime.ScreenEntry = dev.goose.runtime.ScreenEntry { $lambdaParams ->
                |            $functionName(
                |                ${callArgs.joinToString(",\n                ")},
                |            )
                |        }
                |    }
                |}
                |""".trimMargin()
            )
        }
    }

    private fun KSAnnotation.screenArgument(): KSType? =
        arguments.firstOrNull { it.name?.asString() == "screen" || it.name == null }?.value as? KSType

    /** Renders a type with qualified names, generics, and nullability. */
    private fun KSType.render(): String {
        val base = declaration.qualifiedName?.asString() ?: declaration.simpleName.asString()
        val args = if (arguments.isEmpty()) "" else arguments.joinToString(", ", "<", ">") { arg ->
            arg.type?.resolve()?.render() ?: "*"
        }
        val nullable = if (nullability == Nullability.NULLABLE) "?" else ""
        return "$base$args$nullable"
    }
}

class GooseUiProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        GooseUiProcessor(environment.codeGenerator, environment.logger)
}
