# Goose restores persisted back stacks by resolving each screen's serialized JVM class name
# reflectively (Class.forName + its kotlinx serializer). Keep original names for Screen
# implementations so restoration works across minified releases. Apps that register every
# screen explicitly via screenSerializers { } may remove this in their own config.
-keepnames class * implements dev.goose.runtime.Screen

# Object screens carry readResolve (generated by goose-compiler-plugin, or hand-written) so
# Java deserialization returns the singleton after process death. It is only ever invoked
# reflectively by ObjectInputStream, so R8 would otherwise strip it in minified builds.
-keepclassmembers class * implements dev.goose.runtime.Screen {
    java.lang.Object readResolve();
}
